// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc5I720jXrj1s8uFQRvDZPCStgb_HQh3Y',
    appId: '1:951632455737:web:08f616fe0ec2d5ac6705e8',
    messagingSenderId: '951632455737',
    projectId: 'latihan-soal-7b711',
    authDomain: 'latihan-soal-7b711.firebaseapp.com',
    storageBucket: 'latihan-soal-7b711.appspot.com',
    measurementId: 'G-TP0XG3L98B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCq3NdQhg00AvyXEpxPRSKfLJ0Lc8X4QI',
    appId: '1:951632455737:android:ab44e0d7931869bb6705e8',
    messagingSenderId: '951632455737',
    projectId: 'latihan-soal-7b711',
    storageBucket: 'latihan-soal-7b711.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYE8mMV4Cay2jvB9GvIioXD9cAW6JkPNc',
    appId: '1:951632455737:ios:d314055cc193b8336705e8',
    messagingSenderId: '951632455737',
    projectId: 'latihan-soal-7b711',
    storageBucket: 'latihan-soal-7b711.appspot.com',
    androidClientId: '951632455737-4h8vlrdp6c7eo56r0cfj8o6j4ros3ds3.apps.googleusercontent.com',
    iosClientId: '951632455737-1laf49jrt1cin0g6clife70q06vvhvkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.latihanSoal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYE8mMV4Cay2jvB9GvIioXD9cAW6JkPNc',
    appId: '1:951632455737:ios:d314055cc193b8336705e8',
    messagingSenderId: '951632455737',
    projectId: 'latihan-soal-7b711',
    storageBucket: 'latihan-soal-7b711.appspot.com',
    androidClientId: '951632455737-4h8vlrdp6c7eo56r0cfj8o6j4ros3ds3.apps.googleusercontent.com',
    iosClientId: '951632455737-1laf49jrt1cin0g6clife70q06vvhvkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.latihanSoal',
  );
}
